export enum MenuType {
  HOME = 'HOME',
  EXPLORE = 'EXPLORE',
  NOTIFICATIONS = 'NOTIFICATIONS',
  MESSAGES = 'MESSAGES',
  LISTS = 'LISTS',
  BOOKMARKS = 'BOOKMARKS',
  COMMUNITIES = 'COMMUNITIES',
  PROFILE = 'PROFILE'
}
