services:
  twitter-parody-dev:
    image: twitter-parody-dev
    container_name: twitter-parody-dev
    build:
      context: ../.
      dockerfile: ./.devcontainer/Dockerfile
    working_dir: /twitter-parody
    ports:
      - "4208:4200"
    volumes:
      - ..:/twitter-parody:cached
      - /var/run/docker.sock:/var/run/docker.sock
    tty: true
